### ISSUE TITLE
Bug Report：cannot import name 'Buffer' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

### ISSUE THREAD

**Issue by abebe0210** [ydataai/ydata-profiling#1520]
### Current Behaviour

I get this error:
"cannot import name 'Buffer' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)"

when I try importing from ydata_profiling import ProfileReport on google colab.

I wondered if you could help me.

### Expected Behaviour

install nomally

### Data Description

-

### Code that reproduces the bug

```Python
from ydata_profiling import ProfileReport
```

### pandas-profiling version

v4.6.3

### Dependencies

```Text
python==3.10.12
pandas==1.5.3
numpy==1.23.5
```

### OS

google colab

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by sokolegg** [comment]
Same problem in Google Colab

**Comment by ferzkopp** [comment]
Same problem in Notebooks on Azure Synapse spark pools. See attached notebook .ipynb dump with output included.
[Notebook 1-ipynb.txt](https://github.com/ydataai/ydata-profiling/files/13847407/Notebook.1-ipynb.txt)

**Comment by aquemy** [comment]
Hello,

`typing_extensions.Buffer` appears to have been added to Python 3.12.

Maybe you should try to update the package using:
`!pip install -U pandas-profiling`

**Comment by ferzkopp** [comment]
> Hello,
> 
> `typing_extensions.Buffer` appears to have been added to Python 3.12.
> 
> Maybe you should try to update the package using: `!pip install -U pandas-profiling`

Tried - and that didn't work either. Fails with
```
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/typing_extensions.py)
```

Both pandas-profiling and ydata-profiling are tagged with "Requires: Python >=3.7, <3.12" so one would expect it to work on 3.11 (or tagging needs to be updated).

**Comment by nikifori** [comment]
Same problem in Google Colab

**Comment by g7crservice-sajid-f** [comment]
This is still and issue and showstopper.
