### ISSUE TITLE
Unable to install ydata-profiling for Python 3.12.0

### ISSUE THREAD

**Issue by kirankalpathy** [ydataai/ydata-profiling#1510]
### Current Behaviour

I currently have ```Python 3.12.0``` installed on my mac. Trying to install ```ydata_profiling``` package using ```pip3``` and getting the following error:

```
pip3 install -U ydata-profiling    
ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7, <3.11; 4.1.0 Requires-Python >=3.7, <3.12; 4.1.1 Requires-Python >=3.7, <3.12; 4.1.2 Requires-Python >=3.7, <3.12; 4.2.0 Requires-Python >=3.7, <3.12; 4.3.0 Requires-Python >=3.7, <3.12; 4.3.1 Requires-Python >=3.7, <3.12; 4.3.2 Requires-Python >=3.7, <3.12; 4.4.0 Requires-Python >=3.7, <3.12; 4.5.0 Requires-Python >=3.7, <3.12; 4.5.1 Requires-Python >=3.7, <3.12; 4.6.0 Requires-Python >=3.7, <3.12; 4.6.1 Requires-Python >=3.7, <3.12; 4.6.2 Requires-Python >=3.7, <3.12
ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling
```

### Expected Behaviour

Package needs to be installed successfully.

### Data Description

N/A

### Code that reproduces the bug

```Python
pip3 install ydata-profiling
```

### pandas-profiling version

3.2.0

### Dependencies

```Text
pandas==2.1.3
numpy==1.26.2
```

### OS

macos

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by natanael-melo** [comment]
The same error happened to me. 

My **Python version is 3.11.5**, my **Pandas version is 2.0.3**, and my **NumPy version is 1.24.3**. My operating system is **Windows**.

The error that appears is: 
```
"ERROR: Ignored the following versions that require a different python version: 
4.0.0 Requires-Python >=3.7, <3.11; 
4.1.0 Requires-Python >=3.7, <3.12; 
4.1.1 Requires-Python >=3.7, <3.12; 
4.1.2 Requires-Python >=3.7, <3.12; 
4.2.0 Requires-Python >=3.7, <3.12; 
4.3.0 Requires-Python >=3.7, <3.12; 
4.3.1 Requires-Python >=3.7, <3.12; 
4.3.2 Requires-Python >=3.7, <3.12; 
4.4.0 Requires-Python >=3.7, <3.12; 
4.5.0 Requires-Python >=3.7, <3.12; 
4.5.1 Requires-Python >=3.7, <3.12; 
4.6.0 Requires-Python >=3.7, <3.12; 
4.6.1 Requires-Python >=3.7, <3.12; 
4.6.2 Requires-Python >=3.7, <3.12

ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling"
```

**Comment by 0x018** [comment]
same, but on 3.9.5

**Comment by npappin-wsu** [comment]
+1

**Comment by fabclmnt** [comment]
Hi @npappin-wsu , @UItraviolet  and @npappin-wsu ,

thank you for your issue report. Unfortunately, ydata-profiling does not yet available for python 3.12. We are currently working on it, and we expect to have it launched in the beginning of 2024.

**Comment by aquemy** [comment]
@npappin-wsu @UItraviolet  @natanael-melo @kirankalpathy the support for Python 3.12 is blocked by Numba which still does not support it. The support is planned for Numba 0.59 and there is already a release candidate - so as soon as it is an official release, we can update ydata-profiling support as well.

**Comment by ParadoxMachine** [comment]
Same issue with Python 3.10.11 & 3.11.7 The base github repository has the tags for supporting versions 3.7 | 3.8 | 3.9 | 3.10 | 3.11

**Comment by andreas-wolf** [comment]
It seems the official numba release for 3.12 is here: https://github.com/numba/numba/releases/tag/0.59.0

**Comment by aquemy** [comment]
@andreas-wolf nice timing! I prepared the PR yesterday (here: https://github.com/ydataai/ydata-profiling/pull/1521) but unfortunately I am facing an issue with the installation of dependencies.

See here: https://github.com/ydataai/ydata-profiling/actions/runs/7868893919/job/21466934821

```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Any help is welcomed. I found out it is a pretty common error with Python 3.12 but none of the solution I tried worked so far... :(

**Comment by mubbasher-sherani** [comment]
ydata-profiling is working in conda environments successfully using the python's version = Python 3.11.5 it's 26/02/2024 and ydata-profiling is not working in Python 3.12.2 I'm using ydata-profiling using python 3.11.5 and you can use it too.

**Comment by justuswolff-audit** [comment]
I also run into issues with Python 3.11.7. I get an error withe
- "seaborn>=0.13.2",
- "numpy>=1.24.4",
- "pandas>=2.0.3",
at least those are the libraries it complains about in my terminal.

**Comment by fabclmnt** [comment]
@justuswolff-audit can you share more details regarding the environment that you are using (what are packages are installed , etc). 
Based on your message it seems to be incompatibility with the version the versions that ydata-profiling requires.

**Comment by fabclmnt** [comment]
Python 3.12 is supported as of 4.7 version (Match 2024)

**Comment by Tarzanjp** [comment]
I got the same issue and I dont know how to solve it.

ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling

**Comment by gmartinsribeiro** [comment]
@Tarzanjp, Python 3.12 is supported as of 4.7 version (March 2024)

Can you you double check your Python version and share a screenshot?

**Comment by AbdessamadTzn** [comment]
> I got the same issue and I dont know how to solve it.
> 
> ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none) ERROR: No matching distribution found for ydata-profiling
Same issue as @Tarzanjp , I have python 3.13

**Comment by AbdessamadTzn** [comment]
I tried: pip install ydata-profiling==4.7
But still same issue
